### ISSUE TITLE
Doesn't run on windows as there is no rm command

### ISSUE THREAD

**Issue by tarioch** [kopach/lockfix#206]
If I try to run it on windows from the git root, it fails because there is no rm command.

**Comment by Maxim-Mazurok** [comment]
Should be an easy fix by using `npx -y rimraf` instead?

**Comment by yoavain** [comment]
Or use [shelljs](https://www.npmjs.com/package/shelljs) for cross-platform shell commands.
If this project is maintained, I can fork and open a PR.
@kopach?

**Comment by kopach** [comment]
hi @yoavain. Please, go ahead with PR, I would appreciate it. Thanks

**Comment by yoavain** [comment]
@kopach, I opened a PR:
https://github.com/kopach/lockfix/pull/241

**Comment by kopach** [comment]
Merged and released in v 2.1.0
Thanks for contribution everyone. And sorry for late response
